export const ACTIONS = {
  START: 'START',
  STOP: 'STOP',
  JUMP: 'JUMP',
  MOVE: 'MOVE',
  IS_COLLISION: 'IS_COLLISION'
}

export const STATE = {
  STARTED: 'STARTED',
  STOPED: 'STOPED',
  ALIVE: 'ALIVE',
  DEATH: 'DEATH'
}
